// Readiness for AI-assisted development (decided with Sean 2026-10-08). AI coding agents run a
// project's checks every turn; how strict those checks are, whether CI runs them, how often code
// switches them off inline, and whether the repo tells an agent its rules are deterministic,
// cheap signals of how safely agents (and people) can work in it. Read-only file inspection:
// no tools, no network. A census metric; the report shows it without a rating (rubric v2 is
// frozen; a scored row would be a v3 change).

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { stableSort } from "../core/determinism.js";
import { matchesAny } from "../core/glob.js";
import { TEST_GLOBS } from "../lanes/metrics.js";
import { CODE_LANGUAGES } from "./coverage.js";

/** Inline "ignore this" markers, per kind. `as any` is counted in TypeScript only. */
export const SUPPRESSIONS: readonly { readonly kind: string; readonly re: RegExp; readonly languages?: readonly string[] }[] = [
  { kind: "eslint-disable", re: /eslint-disable(?:-next-line|-line)?\b/g },
  { kind: "@ts-ignore", re: /@ts-ignore\b/g },
  { kind: "@ts-expect-error", re: /@ts-expect-error\b/g },
  { kind: "@ts-nocheck", re: /@ts-nocheck\b/g },
  { kind: "as any", re: /\bas any\b/g, languages: ["TypeScript", "TSX", "TypeScript Typings"] },
  { kind: "noqa", re: /#\s*noqa\b/g },
  { kind: "type: ignore", re: /#\s*type:\s*ignore\b/g },
  { kind: "pylint: disable", re: /#\s*pylint:\s*disable/g },
  { kind: "nosemgrep", re: /\bnosemgrep\b/g },
  { kind: "nosec", re: /#\s*nosec\b|\/\/\s*#nosec\b/g },
  { kind: "nolint", re: /\/\/\s*nolint\b/g },
  { kind: "#[allow]", re: /#!?\[allow\(/g },
  { kind: "@SuppressWarnings / @Suppress", re: /@Suppress(?:Warnings)?\(/g },
  { kind: "NOPMD", re: /\bNOPMD\b/g },
  { kind: "rubocop:disable", re: /rubocop:disable\b/g },
  { kind: "@phpstan-ignore", re: /@phpstan-ignore/g },
  { kind: "@psalm-suppress", re: /@psalm-suppress\b/g },
  { kind: "#pragma warning disable", re: /#pragma warning disable\b/g },
  { kind: "[SuppressMessage]", re: /\[SuppressMessage\(/g },
  { kind: "gitleaks:allow", re: /gitleaks:allow\b/g },
];

const CI_GLOBS = [".github/workflows/*.yml", ".github/workflows/*.yaml", ".gitlab-ci.yml", ".circleci/config.yml", "azure-pipelines.yml", "Jenkinsfile",
  "bitbucket-pipelines.yml", ".buildkite/*.yml", ".travis.yml", ".drone.yml", ".woodpecker.yml", ".woodpecker/*.yml"];
const CI_RUNS = {
  lint: /\b(?:lint|eslint|biome|oxlint|ruff|flake8|pylint|golangci-lint|clippy|rubocop|phpstan|psalm|ktlint|detekt|dotnet format)\b/i,
  types: /\b(?:tsc|typecheck|type-check|mypy|pyright|go vet|cargo check)\b/i,
  tests: /\b(?:test|tests|pytest|vitest|jest|mocha|go test|cargo test|rspec|phpunit|dotnet test|playwright|gradle(?:w)? (?:test|check)|mvn (?:test|verify))\b/i,
};
/** Files that tell an AI agent the project's rules (vendor-neutral and vendor-specific). */
const AGENT_GLOBS = ["**/AGENTS.md", "**/CLAUDE.md", "**/GEMINI.md", "**/CONVENTIONS.md", ".cursorrules", ".cursor/rules/**", ".github/copilot-instructions.md", ".windsurfrules", ".clinerules"];

const TOP_FILES = 10;
const GENERATED_NAME = /(?:\.gen\.|\.generated\.|_pb2?\.py$|\.pb\.go$|_pb\.d\.ts$|\.g\.cs$|\.Designer\.cs$)/;
const GENERATED_HEADER = /@generated|DO NOT EDIT|auto-?generated|generated by/i;

/** A file a tool wrote, by name or by its header's own marker (first 5 lines). */
export function isGenerated(file: string, text: string): boolean {
  return GENERATED_NAME.test(file) || GENERATED_HEADER.test(text.split("\n").slice(0, 5).join("\n"));
}

interface CensusFiles { readonly [file: string]: { readonly code: number; readonly language: string } }

/** tsconfig is JSON with comments and trailing commas. Unparseable → null. */
function readJsonc(text: string): Record<string, unknown> | null {
  const stripped = text.replace(/("(?:[^"\\]|\\.)*")|\/\/[^\n]*|\/\*[\s\S]*?\*\//g, (m, str: string | undefined) => str ?? "").replace(/,(\s*[}\]])/g, "$1");
  try {
    const v: unknown = JSON.parse(stripped);
    return typeof v === "object" && v !== null && !Array.isArray(v) ? (v as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

export function readinessMetrics(root: string, allFiles: readonly string[], census: CensusFiles): Record<string, unknown> {
  const files = allFiles.filter((f) => !f.split("/").includes("node_modules"));
  // Suppressions in program source (the census's code files). Density and top files cover
  // production code only (test mocks and generated files lean on `as any` by design; the same
  // call as duplication, decided 2026-10-08); the totals keep tests and generated code visible.
  const byKind: Record<string, number> = {};
  const perFile: { file: string; count: number }[] = [];
  const where = { production: 0, tests: 0, generated: 0 };
  let code = 0;
  for (const [file, m] of Object.entries(census)) {
    if (!CODE_LANGUAGES.has(m.language) || file.split("/").includes("node_modules")) continue;
    const abs = path.join(root, file);
    if (!existsSync(abs)) continue;
    const text = readFileSync(abs, "utf8");
    const kind = isGenerated(file, text) ? "generated" : matchesAny(file, TEST_GLOBS) ? "tests" : "production";
    if (kind === "production") code += m.code;
    let n = 0;
    for (const s of SUPPRESSIONS) {
      if (s.languages !== undefined && !s.languages.includes(m.language)) continue;
      const hits = text.match(s.re)?.length ?? 0;
      if (hits > 0 && kind === "production") byKind[s.kind] = (byKind[s.kind] ?? 0) + hits;
      n += hits;
    }
    where[kind] += n;
    if (n > 0 && kind === "production") perFile.push({ file, count: n });
  }
  const total = where.production;

  const tsconfigs = files.filter((f) => /(?:^|\/)tsconfig[^/]*\.json$/.test(f)).map((f) => {
    const doc = readJsonc(readFileSync(path.join(root, f), "utf8"));
    const opts = (doc?.["compilerOptions"] ?? {}) as Record<string, unknown>;
    const strict = doc === null ? "unreadable" : opts["strict"] === true ? "on" : opts["strict"] === false ? "off" : typeof doc["extends"] === "string" || Array.isArray(doc["extends"]) ? "inherited" : "off";
    return { file: f, strict, no_unchecked_indexed_access: opts["noUncheckedIndexedAccess"] === true };
  });

  const ci = files.filter((f) => matchesAny(f, CI_GLOBS));
  const ciText = ci.map((f) => readFileSync(path.join(root, f), "utf8")).join("\n");

  return {
    suppressions: {
      total, tests: where.tests, generated: where.generated, per_kloc_x10: code === 0 ? 0 : Math.floor((total * 10000) / code),
      by_kind: byKind,
      top_files: stableSort(perFile, (x) => [-x.count, x.file]).slice(0, TOP_FILES),
    },
    typescript: { configs: tsconfigs },
    ci: { files: ci, lint: CI_RUNS.lint.test(ciText), types: CI_RUNS.types.test(ciText), tests: CI_RUNS.tests.test(ciText) },
    agent_files: files.filter((f) => matchesAny(f, AGENT_GLOBS)),
  };
}
