// debug/<id>/root-cause.md (PRD §11 step 7; M5 W3): a pure function of the debug's events.
// The consultant's prose (mechanism, notes) lives in keep-blocks and survives regeneration;
// everything else is regenerated byte-identically from the record.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { canonicalJson } from "../core/determinism.js";
import { applyKeeps, code, esc, extractKeeps, keep, table } from "../address/markdown.js";
import type { DebugState } from "./state.js";

const short = (sha: string) => sha.slice(0, 12);

export function renderRootCause(d: DebugState, engagement: string): string {
  const s = (v: string) => canonicalJson(v);
  const c = d.conclusion;
  const parts = [
    "---",
    `title: ${s(`Root cause: ${d.id}`)}`,
    `engagement: ${s(engagement)}`,
    `debug: ${s(d.id)}`,
    `commit: ${s(d.commit)}`,
    `outcome: ${s(c?.outcome ?? "open")}`,
    "---",
    "",
    "# Symptom",
    "",
    esc(d.symptom),
  ];
  const intake = [["Expected", d.expected], ["Actual", d.actual], ["Environment", d.environment], ["First seen", d.firstSeen]].filter((x): x is [string, string] => x[1] !== undefined);
  if (d.findingId !== undefined) intake.unshift(["From finding", d.findingId]);
  if (intake.length > 0) parts.push("", table(["", ""], intake.map(([k, v]) => [k, esc(v)])));

  parts.push("", "# Conclusion", "");
  if (c === undefined) parts.push("Not concluded yet.");
  else {
    const rows: string[][] = [["Outcome", c.outcome]];
    if (c.hypothesisId !== undefined) rows.push(["Confirmed hypothesis", c.hypothesisId]);
    if (c.introducingCommit !== undefined) rows.push(["Introducing commit", code(c.introducingCommit)]);
    parts.push(esc(c.summary), "", table(["", ""], rows));
  }
  parts.push("", "## Mechanism", "", keep("mechanism", "_How the defect produces the symptom. Preserved across regeneration._"));

  const repros = d.runs.filter((r) => r.kind === "repro");
  parts.push("", "# Reproduction", "", "The repro follows the `git bisect run` contract: exit 0 means the bug is absent, 125 means the run can't tell, and any other exit means the bug is present.", "");
  parts.push(repros.length === 0 ? "No repro run recorded." : table(["Run", "Commit", "Exit", "Result", "Log"], repros.map((r) => [r.runId, code(short(r.commit)), String(r.exitCode), r.outcome, code(r.logRef)])));

  if (d.bisect !== undefined) {
    const b = d.bisect;
    const bisects = d.runs.filter((r) => r.kind === "bisect");
    parts.push("", "# Localization", "",
      b.firstBad.length === 1
        ? `Bisected between ${code(short(b.good))} (good) and ${code(short(b.bad))} (bad): the first bad commit is ${code(b.firstBad[0] ?? "")}.`
        : `Bisected between ${code(short(b.good))} (good) and ${code(short(b.bad))} (bad). Some commits couldn't be tested; the first bad commit is one of ${b.firstBad.map((x) => code(short(x))).join(", ")}.`,
      "", table(["Run", "Commit", "Exit", "Result"], bisects.map((r) => [r.runId, code(short(r.commit)), String(r.exitCode), r.outcome])));
  }

  parts.push("", "# Hypotheses", "");
  if (d.hypotheses.length === 0) parts.push("None recorded.");
  else {
    parts.push(table(["ID", "State", "Hypothesis", "Decided by"], d.hypotheses.map((h) => [
      h.id, h.state, `${h.source === "llm" ? "(AI-suggested) " : ""}${esc(h.text)}`, h.decidedBy === undefined ? "" : `${h.decidedBy}: ${esc(h.reason ?? "")}`,
    ])));
  }

  const guards = d.runs.filter((r) => r.kind === "guard-without-fix" || r.kind === "guard-with-fix");
  if (guards.length > 0) {
    parts.push("", "# Regression guard", "", table(["Run", "Kind", "Commit", "Exit", "Result"], guards.map((r) => [r.runId, r.kind, code(short(r.commit)), String(r.exitCode), r.outcome])));
  }

  parts.push("", "# Evidence", "", "Every run, with the hash of its log as recorded in the engagement's event log.", "",
    d.runs.length === 0 ? "No runs." : table(["Run", "Kind", "Script", "Log", "Log hash"], d.runs.map((r) => [r.runId, r.kind, code(r.scriptHash.slice(7, 19)), code(r.logRef), code(r.logHash.slice(7, 19))])));
  parts.push("", "# Notes", "", keep("notes", "_Consultant notes. Preserved across regeneration._"));
  return `${parts.join("\n")}\n`;
}

/** Write root-cause.md, keeping the consultant's keep-blocks. */
export function writeRootCause(file: string, d: DebugState, engagement: string): void {
  const generated = renderRootCause(d, engagement);
  writeFileSync(file, existsSync(file) ? applyKeeps(generated, extractKeeps(readFileSync(file, "utf8"))) : generated);
}
