// The container toolchain image (M3 W0, AC1). Built LOCALLY from verified artifacts, never
// pulled from a vendor (PRD §14.3):
//   - pinned base images by multi-arch index digest (toolchain/sandbox-images.yml)
//   - every tool binary downloaded and sha256-verified inside the build (toolchain/image/fetch.py)
//   - Python tools from a hash-locked requirements file (--require-hashes --no-deps)
//   - node-tools via `npm ci --ignore-scripts` from its lockfile
//   - Debian packages (git) from a FIXED snapshot.debian.org timestamp
// The build context is generated deterministically from the repo; its hash names the image tag.

import { copyFileSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { assetPath, readAsset } from "../core/assets.js";
import { canonicalJson, stableSort } from "../core/determinism.js";
import { InternalError, RefusedError } from "../core/errors.js";
import { run } from "../core/exec.js";
import { treeHash } from "../sandbox/deps.js";
import { imageRef, type Runtime } from "../sandbox/runtime.js";
import { ESLINT_BASELINE } from "./install.js";
import { loadManifest } from "./manifest.js";

/**
 * Debian snapshot used for apt inside the image: packages are frozen at this instant.
 * It must NOT predate the pinned base image build (2026-10-06), or apt sees the base image's
 * packages as newer than the snapshot's and refuses (verified). Bump it with scripts/pin-images.ts.
 */
export const DEBIAN_SNAPSHOT = "20261007T000000Z";
/** Where tools live inside the image (mirrors the host's $RADR_HOME/tools layout). */
export const IMAGE_TOOLS = "/opt/radr/tools";
export const IMAGE_NODE_TOOLS = "/opt/radr/node-tools";
export const IMAGE_CONFIGS = "/opt/radr/configs";
/** The image's Python venv (hash-locked py-tools: lizard, checkov, scancode). */
export const IMAGE_PY = "/opt/radr/py";
/** Python tools whose versions are recorded per run (requirements.txt name → tool name). */
export const PY_TOOLS: Readonly<Record<string, string>> = { lizard: "lizard", checkov: "checkov", scancode: "scancode-toolkit-mini" };

/** Pinned versions of the Python tools, read from the hash-locked requirements. */
export function pyToolVersions(): Record<string, string> {
  const req = readAsset("toolchain/py-tools/requirements.txt");
  const out: Record<string, string> = {};
  for (const [tool, pkg] of Object.entries(PY_TOOLS)) {
    const m = new RegExp(`^${pkg.replace(/[-.]/g, "[-_.]")}==([^\\s]+)`, "m").exec(req);
    if (m?.[1] === undefined) throw new InternalError(`toolchain/py-tools/requirements.txt does not pin ${pkg}`);
    out[tool] = m[1];
  }
  return out;
}
export const IMAGE_NODE = "/usr/local/bin/node";
const RUNTIME_ENV = ["PATH", "HOME", "XDG_RUNTIME_DIR", "XDG_CONFIG_HOME", "XDG_DATA_HOME", "CONTAINER_HOST", "CONTAINER_CONNECTION", "DOCKER_HOST", "DOCKER_CONTEXT", "DOCKER_CONFIG"];
const BUILD_TIMEOUT_MS = 60 * 60 * 1000;

export function containerfile(): string {
  return `# GENERATED by radr (src/toolchain/image.ts). Do not edit: change the manifest and rebuild.
FROM ${imageRef("node")} AS nodetools
WORKDIR ${IMAGE_NODE_TOOLS}
COPY node-tools/package.json node-tools/package-lock.json ./
RUN npm ci --ignore-scripts --no-audit --no-fund --loglevel=error
COPY node-tools/${ESLINT_BASELINE} ./

FROM ${imageRef("python")}
ARG TARGETARCH
# Debian packages from a FIXED snapshot (reproducible apt, signature-checked): git (history,
# gitleaks), libmagic1 + libmagic-mgc (ScanCode file-type detection and its magic database).
RUN rm -f /etc/apt/sources.list.d/debian.sources \\
 && printf 'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/${DEBIAN_SNAPSHOT} bookworm main\\ndeb [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/${DEBIAN_SNAPSHOT} bookworm-security main\\n' > /etc/apt/sources.list.d/snapshot.list \\
 && apt-get -o Acquire::Check-Valid-Until=false update \\
 && apt-get install -y --no-install-recommends git libmagic1 libmagic-mgc \\
 && rm -rf /var/lib/apt/lists/*
COPY --from=nodetools /usr/local/bin/node ${IMAGE_NODE}
COPY --from=nodetools ${IMAGE_NODE_TOOLS} ${IMAGE_NODE_TOOLS}
COPY fetch.py tools.json /opt/radr/build/
RUN python /opt/radr/build/fetch.py /opt/radr/build/tools.json "$TARGETARCH" ${IMAGE_TOOLS}
COPY py-tools/requirements.txt /opt/radr/build/requirements.txt
RUN python -m venv /opt/radr/py \\
 && /opt/radr/py/bin/pip install --no-cache-dir --disable-pip-version-check --require-hashes --no-deps -r /opt/radr/build/requirements.txt
COPY configs ${IMAGE_CONFIGS}
ENV PATH=/opt/radr/py/bin:/usr/local/bin:/usr/bin:/bin PYTHONDONTWRITEBYTECODE=1
LABEL org.opencontainers.image.title="radr-toolchain" org.opencontainers.image.source="radr"
`;
}

/** Linux tool specs per platform, from the manifest (the image's only source of pins). */
export function toolSpecs(): Record<string, unknown[]> {
  const m = loadManifest();
  const out: Record<string, unknown[]> = {};
  for (const platform of ["linux-x64", "linux-arm64"] as const) {
    out[platform] = stableSort(Object.entries(m.tools), ([n]) => n).map(([tool, t]) => ({ tool, version: t.version, ...t.platforms[platform] }));
  }
  return out;
}

/** Write the build context; returns its directory and content hash (the image tag). */
export function writeContext(dir: string): { dir: string; hash: string } {
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(path.join(dir, "node-tools"), { recursive: true });
  mkdirSync(path.join(dir, "py-tools"), { recursive: true });
  mkdirSync(path.join(dir, "configs"), { recursive: true });
  writeFileSync(path.join(dir, "Containerfile"), containerfile());
  writeFileSync(path.join(dir, "tools.json"), canonicalJson(toolSpecs()));
  copyFileSync(assetPath("toolchain/image/fetch.py"), path.join(dir, "fetch.py"));
  copyFileSync(assetPath("toolchain/py-tools/requirements.txt"), path.join(dir, "py-tools", "requirements.txt"));
  for (const f of ["package.json", "package-lock.json"]) copyFileSync(assetPath(`toolchain/node-tools/${f}`), path.join(dir, "node-tools", f));
  copyFileSync(assetPath(`toolchain/configs/eslint/${ESLINT_BASELINE}`), path.join(dir, "node-tools", ESLINT_BASELINE));
  writeFileSync(path.join(dir, "configs", "ruff.toml"), readAsset("toolchain/configs/ruff/ruff.toml"));
  return { dir, hash: treeHash(dir).hash };
}

export function imageTag(contextHash: string): string {
  return `localhost/radr-toolchain:${contextHash.slice(7, 23)}`;
}

/** Host arch as the container build expects it. */
export async function runtimeArch(rt: Runtime): Promise<"amd64" | "arm64"> {
  const fmt = rt.name === "podman" ? "{{.Host.Arch}}" : "{{.Architecture}}";
  const r = await run({ command: rt.name, args: ["info", "--format", fmt], cwd: "/", inheritEnv: RUNTIME_ENV });
  const arch = r.stdout.toString().trim();
  if (arch === "amd64" || arch === "x86_64") return "amd64";
  if (arch === "arm64" || arch === "aarch64") return "arm64";
  throw new RefusedError(`unsupported container architecture "${arch}"`);
}

export async function imageId(rt: Runtime, ref: string): Promise<string | undefined> {
  const r = await run({ command: rt.name, args: ["image", "inspect", "--format", "{{.Id}}", ref], cwd: "/", inheritEnv: RUNTIME_ENV });
  const id = r.stdout.toString().trim().replace(/^sha256:/, "");
  return r.outcome === "ok" && /^[0-9a-f]{64}$/.test(id) ? `sha256:${id}` : undefined;
}

export interface BuiltImage {
  readonly tag: string;
  readonly id: string;
  readonly contextHash: string;
  readonly reused: boolean;
}

/** Build (or reuse) the toolchain image for the current context. Network: downloads artifacts. */
export async function buildImage(home: string, rt: Runtime, log: (line: string) => void): Promise<BuiltImage> {
  const ctx = writeContext(path.join(home, "build", "toolchain-image"));
  const tag = imageTag(ctx.hash);
  const existing = await imageId(rt, tag);
  if (existing !== undefined) return { tag, id: existing, contextHash: ctx.hash, reused: true };
  const arch = await runtimeArch(rt);
  log(`building ${tag} for linux/${arch} (downloads and verifies every pinned artifact)…`);
  const r = await run({
    command: rt.name,
    args: ["build", "--pull=never", "--build-arg", `TARGETARCH=${arch}`, "-t", tag, "-f", path.join(ctx.dir, "Containerfile"), ctx.dir],
    cwd: ctx.dir, inheritEnv: RUNTIME_ENV, timeoutMs: BUILD_TIMEOUT_MS,
  });
  if (r.outcome !== "ok") throw new RefusedError(`toolchain image build failed: ${r.stderr.toString().trim().split("\n").slice(-6).join(" | ")}`);
  const id = await imageId(rt, tag);
  if (id === undefined) throw new RefusedError(`built ${tag} but cannot inspect it`);
  return { tag, id, contextHash: ctx.hash, reused: false };
}

/** Tool binary paths INSIDE the image for a platform (mirrors the host layout). */
export function imageBins(platform: "linux-x64" | "linux-arm64"): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [tool, t] of Object.entries(loadManifest().tools)) out[tool] = `${IMAGE_TOOLS}/${tool}/${t.version}/${t.platforms[platform].bin}`;
  out["checkov"] = `${IMAGE_PY}/bin/checkov`;
  out["scancode"] = `${IMAGE_PY}/bin/scancode`;
  return out;
}

/** The current context's image, if it has been built: what a container-mode scope locks. */
export async function currentImage(home: string, rt: Runtime): Promise<{ tag: string; id: string; contextHash: string; platform: "linux-x64" | "linux-arm64" } | undefined> {
  const ctx = writeContext(path.join(home, "build", "toolchain-image"));
  const tag = imageTag(ctx.hash);
  const id = await imageId(rt, tag);
  if (id === undefined) return undefined;
  const arch = await runtimeArch(rt);
  return { tag, id, contextHash: ctx.hash, platform: arch === "amd64" ? "linux-x64" : "linux-arm64" };
}
