// Stack sandbox images (M3 W5). Each new stack runs client code in an image built LOCALLY from a
// pinned base (toolchain/sandbox-images.yml, by index digest) plus extra tools pinned in
// toolchain/sandbox-tools.yml (each sha256 checked during the build, in a separate fetch stage) or
// installed by a verifying package manager (rustup components; bundler with lockfile CHECKSUMS).
// The tag is the build context's content hash, so the tag alone says what is inside; .NET runs
// in the pinned SDK image as-is.
//
// Images are built by `radr deps warm` (the online step) or `radr tools build-image --stack`.

import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { assetPath, readAsset } from "../core/assets.js";
import { canonicalJson, stableSort } from "../core/determinism.js";
import { InternalError, RefusedError } from "../core/errors.js";
import { run } from "../core/exec.js";
import { parseYaml } from "../core/yaml.js";
import { DEBIAN_SNAPSHOT, imageId, runtimeArch } from "../toolchain/image.js";
import { treeHash } from "./deps.js";
import { imageRef, type Runtime } from "./runtime.js";

/** Stacks whose sandbox needs a locally built image (.NET uses the pinned SDK image directly). */
export const BUILT_STACKS = ["go", "rust", "java-kotlin", "php", "ruby"] as const;
export type BuiltStack = (typeof BUILT_STACKS)[number];

const BASE: Readonly<Record<BuiltStack, string>> = { go: "go", rust: "rust", "java-kotlin": "jvm", php: "php", ruby: "ruby" };
export const SANDBOX_TOOLS = "/opt/radr/tools";
export const RUBOCOP_DIR = "/opt/radr/rubocop";
const RUNTIME_ENV = ["PATH", "HOME", "XDG_RUNTIME_DIR", "XDG_CONFIG_HOME", "XDG_DATA_HOME", "CONTAINER_HOST", "CONTAINER_CONNECTION", "DOCKER_HOST", "DOCKER_CONTEXT", "DOCKER_CONFIG"];

interface ToolPin { readonly version: string; readonly stacks: readonly string[]; readonly platforms: Readonly<Record<"linux-x64" | "linux-arm64", { url: string; sha256: string; archive: string; bin: string }>> }

export function sandboxTools(): Readonly<Record<string, ToolPin>> {
  const doc = parseYaml(readAsset("toolchain/sandbox-tools.yml"), "toolchain/sandbox-tools.yml") as { tools?: Record<string, ToolPin> };
  if (doc.tools === undefined) throw new InternalError("toolchain/sandbox-tools.yml has no tools");
  return doc.tools;
}

function version(tool: string): string {
  const t = sandboxTools()[tool];
  if (t === undefined) throw new InternalError(`toolchain/sandbox-tools.yml does not pin ${tool}`);
  return t.version;
}

/** Absolute paths of the pinned tools inside the stack images (arch-independent by construction). */
export function sandboxToolPaths(): { mvn: string; pmd: string; phpstan: string; composer: string } {
  return {
    mvn: `${SANDBOX_TOOLS}/maven/${version("maven")}/apache-maven-${version("maven")}/bin/mvn`,
    pmd: `${SANDBOX_TOOLS}/pmd/${version("pmd")}/pmd-bin-${version("pmd")}/bin/pmd`,
    phpstan: `${SANDBOX_TOOLS}/phpstan/${version("phpstan")}/phpstan.phar`,
    composer: `${SANDBOX_TOOLS}/composer/${version("composer")}/composer.phar`,
  };
}

const FETCH_STAGE = (): string => `FROM ${imageRef("python")} AS fetch
ARG TARGETARCH
COPY fetch.py tools.json /opt/radr/build/
RUN python /opt/radr/build/fetch.py /opt/radr/build/tools.json "$TARGETARCH" ${SANDBOX_TOOLS}

`;

export function stackContainerfile(stack: BuiltStack): string {
  const head = `# GENERATED by radr (src/sandbox/stack-images.ts). Do not edit: change the pins and rebuild.\n`;
  const label = `LABEL org.opencontainers.image.title="radr-sandbox-${stack}" org.opencontainers.image.source="radr"\n`;
  switch (stack) {
    case "go": {
      const v = version("golangci-lint");
      return `${head}${FETCH_STAGE()}FROM ${imageRef("go")}
ARG TARGETARCH
COPY --from=fetch ${SANDBOX_TOOLS} ${SANDBOX_TOOLS}
RUN ln -s ${SANDBOX_TOOLS}/golangci-lint/${v}/golangci-lint-${v}-linux-$TARGETARCH/golangci-lint /usr/local/bin/golangci-lint
ENV GOTOOLCHAIN=local GOFLAGS=-buildvcs=false GOTELEMETRY=off
${label}`;
    }
    case "rust":
      // rustup verifies each component against the channel manifest's sha256.
      return `${head}FROM ${imageRef("rust")}
RUN rustup component add clippy && chmod -R a+rX /usr/local/rustup /usr/local/cargo
${label}`;
    case "java-kotlin":
      return `${head}${FETCH_STAGE()}FROM ${imageRef("jvm")}
COPY --from=fetch ${SANDBOX_TOOLS} ${SANDBOX_TOOLS}
${label}`;
    case "php":
      return `${head}${FETCH_STAGE()}FROM ${imageRef("php")}
# Composer needs unzip (dist archives) and git (source fallback): from a FIXED Debian snapshot.
RUN rm -f /etc/apt/sources.list.d/debian.sources \\
 && printf 'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/${DEBIAN_SNAPSHOT} bookworm main\\ndeb [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/${DEBIAN_SNAPSHOT} bookworm-security main\\n' > /etc/apt/sources.list.d/snapshot.list \\
 && apt-get -o Acquire::Check-Valid-Until=false update \\
 && apt-get install -y --no-install-recommends git unzip \\
 && rm -rf /var/lib/apt/lists/*
COPY --from=fetch ${SANDBOX_TOOLS} ${SANDBOX_TOOLS}
${label}`;
    case "ruby":
      // BUNDLE_FROZEN + the lockfile's CHECKSUMS: bundler verifies every gem's sha256.
      return `${head}FROM ${imageRef("ruby")}
COPY rubocop/Gemfile rubocop/Gemfile.lock ${RUBOCOP_DIR}/
RUN cd ${RUBOCOP_DIR} && BUNDLE_FROZEN=true BUNDLE_PATH=${RUBOCOP_DIR}/vendor bundle install --quiet && chmod -R a+rX ${RUBOCOP_DIR}
${label}`;
  }
}

/** The stack's pinned tools per platform, in fetch.py's input shape. */
function toolsJson(stack: BuiltStack): Record<string, unknown[]> {
  const tools = stableSort(Object.entries(sandboxTools()).filter(([, t]) => t.stacks.includes(stack)), ([n]) => n);
  const out: Record<string, unknown[]> = {};
  for (const platform of ["linux-x64", "linux-arm64"] as const) out[platform] = tools.map(([tool, t]) => ({ tool, version: t.version, ...t.platforms[platform] }));
  return out;
}

export function writeStackContext(dir: string, stack: BuiltStack): { dir: string; hash: string } {
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, "Containerfile"), stackContainerfile(stack));
  if (stackContainerfile(stack).includes("AS fetch")) {
    copyFileSync(assetPath("toolchain/image/fetch.py"), path.join(dir, "fetch.py"));
    writeFileSync(path.join(dir, "tools.json"), canonicalJson(toolsJson(stack)));
  }
  if (stack === "ruby") {
    mkdirSync(path.join(dir, "rubocop"));
    for (const f of ["Gemfile", "Gemfile.lock"]) copyFileSync(assetPath(`toolchain/sandbox/rubocop/${f}`), path.join(dir, "rubocop", f));
  }
  return { dir, hash: treeHash(dir).hash };
}

const contextDir = (home: string, stack: BuiltStack): string => path.join(home, "build", `sandbox-${stack}`);

/** The image tag for a stack's CURRENT pins (no runtime needed: the tag is the context hash). */
export function stackImageTag(home: string, stack: BuiltStack): string {
  const ctx = writeStackContext(contextDir(home, stack), stack);
  return `localhost/radr-sandbox-${stack}:${ctx.hash.slice(7, 23)}`;
}

/** Image a sandboxed step runs in, for a stack (and, for .NET, the SDK major). */
export function sandboxImageFor(home: string, stack: string, dotnetSdk: "8.0" | "10.0" = "8.0"): string {
  if (stack === "typescript-javascript") return imageRef("node");
  if (stack === "python") return imageRef("python");
  if (stack === "csharp") return imageRef(dotnetSdk === "10.0" ? "dotnet-10" : "dotnet-8");
  if ((BUILT_STACKS as readonly string[]).includes(stack)) return stackImageTag(home, stack as BuiltStack);
  throw new InternalError(`no sandbox image for stack "${stack}"`);
}

async function pull(rt: Runtime, ref: string): Promise<"present" | "pulled"> {
  if ((await imageId(rt, ref)) !== undefined) return "present";
  const r = await run({ command: rt.name, args: ["pull", "--quiet", ref], cwd: "/", inheritEnv: RUNTIME_ENV, timeoutMs: 30 * 60 * 1000 });
  if (r.outcome !== "ok") throw new RefusedError(`pulling ${ref} failed: ${r.stderr.toString().trim().split("\n").at(-1) ?? r.outcome}`);
  return "pulled";
}

/** Make sure the image a stack needs exists locally: pull a pinned image, or build a stack image (network). */
export async function ensureStackImage(home: string, rt: Runtime, stack: string, log: (line: string) => void, dotnetSdk: "8.0" | "10.0" = "8.0"): Promise<string> {
  if (!(BUILT_STACKS as readonly string[]).includes(stack)) {
    const ref = sandboxImageFor(home, stack, dotnetSdk);
    if ((await pull(rt, ref)) === "pulled") log(`pulled ${ref}`);
    return ref;
  }
  const s = stack as BuiltStack;
  const tag = stackImageTag(home, s);
  if ((await imageId(rt, tag)) !== undefined) return tag;
  const dir = contextDir(home, s);
  if (!existsSync(path.join(dir, "Containerfile"))) writeStackContext(dir, s);
  // Bases are pinned by digest; --pull=never below means nothing unpinned can sneak in.
  await pull(rt, imageRef(BASE[s]));
  if (stackContainerfile(s).includes("AS fetch")) await pull(rt, imageRef("python"));
  const arch = await runtimeArch(rt);
  log(`building ${tag} for linux/${arch} (pinned base, verified tools)…`);
  const r = await run({
    command: rt.name, args: ["build", "--pull=never", "--build-arg", `TARGETARCH=${arch}`, "-t", tag, "-f", path.join(dir, "Containerfile"), dir],
    cwd: dir, inheritEnv: RUNTIME_ENV, timeoutMs: 60 * 60 * 1000,
  });
  if (r.outcome !== "ok") throw new RefusedError(`${stack} sandbox image build failed: ${r.stderr.toString().trim().split("\n").slice(-6).join(" | ")}`);
  return tag;
}

/** Every W5 stack's sandbox image ref (keys: stack, or csharp-<sdk>): for the Toolbox and toolchain.lock. */
export function stackImages(home: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const s of BUILT_STACKS) out[s] = stackImageTag(home, s);
  out["csharp-8.0"] = imageRef("dotnet-8");
  out["csharp-10.0"] = imageRef("dotnet-10");
  return out;
}
