// Maintainer script: resolve sandbox base images to their multi-arch INDEX digests and write
// toolchain/sandbox-images.yml. An index digest pins every architecture at once, so arm64
// and x64 hosts run the same pinned image content for their platform.
//
//   npm run build && node dist/scripts/pin-images.js

import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { stringify } from "yaml";

const IMAGES: Readonly<Record<string, { registry?: "docker" | "mcr"; repo: string; tag: string; purpose: string }>> = {
  node: { repo: "library/node", tag: "24-bookworm-slim", purpose: "typescript-javascript stack" },
  python: { repo: "library/python", tag: "3.12-slim-bookworm", purpose: "python stack" },
  // M3 W5: bases for the locally built stack sandbox images (src/sandbox/stack-images.ts).
  go: { repo: "library/golang", tag: "1.27-bookworm", purpose: "go stack (base)" },
  rust: { repo: "library/rust", tag: "1.99-bookworm", purpose: "rust stack (base)" },
  jvm: { repo: "library/eclipse-temurin", tag: "21-jdk", purpose: "java-kotlin stack (base)" },
  php: { repo: "library/php", tag: "8.4-cli-bookworm", purpose: "php stack (base)" },
  ruby: { repo: "library/ruby", tag: "3.4-bookworm", purpose: "ruby stack (base)" },
  "dotnet-8": { registry: "mcr", repo: "dotnet/sdk", tag: "8.0", purpose: "csharp stack, net8 and earlier" },
  "dotnet-10": { registry: "mcr", repo: "dotnet/sdk", tag: "10.0", purpose: "csharp stack, net9/net10" },
};
const INDEX_TYPES = ["application/vnd.oci.image.index.v1+json", "application/vnd.docker.distribution.manifest.list.v2+json"];
const REQUIRED_PLATFORMS = ["linux/amd64", "linux/arm64"];

async function json(url: string, headers: Record<string, string> = {}): Promise<unknown> {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`GET ${url}: ${res.status}`);
  return res.json();
}

async function resolve(repo: string, tag: string, registry: "docker" | "mcr" = "docker"): Promise<string> {
  const base = registry === "mcr" ? "https://mcr.microsoft.com" : "https://registry-1.docker.io";
  const auth: Record<string, string> = registry === "mcr" ? {}
    : { Authorization: `Bearer ${((await json(`https://auth.docker.io/token?service=registry.docker.io&scope=repository:${repo}:pull`)) as { token: string }).token}` };
  const headers = { ...auth, Accept: INDEX_TYPES.join(", ") };
  const head = await fetch(`${base}/v2/${repo}/manifests/${tag}`, { method: "HEAD", headers });
  const digest = head.headers.get("docker-content-digest");
  if (!head.ok || digest === null || !/^sha256:[0-9a-f]{64}$/.test(digest)) throw new Error(`${repo}:${tag}: no index digest`);
  const index = (await json(`${base}/v2/${repo}/manifests/${digest}`, headers)) as { manifests?: { platform?: { os: string; architecture: string } }[] };
  const platforms = new Set((index.manifests ?? []).map((m) => `${m.platform?.os ?? ""}/${m.platform?.architecture ?? ""}`));
  for (const p of REQUIRED_PLATFORMS) if (!platforms.has(p)) throw new Error(`${repo}:${tag} lacks ${p}`);
  return digest;
}

async function main(): Promise<void> {
  const images: Record<string, unknown> = {};
  for (const [name, spec] of Object.entries(IMAGES)) {
    const digest = await resolve(spec.repo, spec.tag, spec.registry);
    images[name] = { ref: `${spec.registry === "mcr" ? "mcr.microsoft.com" : "docker.io"}/${spec.repo}@${digest}`, tag: spec.tag, purpose: spec.purpose, platforms: REQUIRED_PLATFORMS };
    process.stdout.write(`pinned ${name} ${spec.tag} ${digest}\n`);
  }
  const header = "# toolchain/sandbox-images.yml: GENERATED by scripts/pin-images.ts. Do not edit by hand.\n" +
    "# Multi-arch index digests from the registry; part of toolchain.lock (and so the scope fingerprint).\n";
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
  writeFileSync(path.join(root, "toolchain/sandbox-images.yml"), header + stringify({ version: 1, images }, { lineWidth: 0, aliasDuplicateObjects: false }));
}

if (process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
