// Maintainer script (M3 W0): hash-locked Python tools for the toolchain image.
//
//   npm run build && node dist/scripts/pin-pytools.js
//
// 1. Resolve toolchain/py-tools/requirements.in to an exact dependency tree with
//    `pip install --dry-run --report` INSIDE the pinned Python sandbox image (same Python as
//    the toolchain image), so markers resolve for the real target interpreter.
// 2. For every resolved name==version, take the sha256 of EVERY distribution file from PyPI,
//    so `pip install --require-hashes` works on both linux/amd64 and linux/arm64.
// 3. Write toolchain/py-tools/requirements.txt (sorted; one --hash per file).

import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { run } from "../src/core/exec.js";
import { compareCodePoints } from "../src/core/determinism.js";
import { detectRuntime, imageRef } from "../src/sandbox/runtime.js";

interface Report { install: { metadata: { name: string; version: string } }[] }
interface PypiRelease { urls: { digests: { sha256: string }; filename: string }[] }

const norm = (n: string): string => n.toLowerCase().replace(/[-_.]+/g, "-");

async function main(): Promise<void> {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
  const dir = path.join(root, "toolchain/py-tools");
  const rt = await detectRuntime(process.env);
  if (rt === undefined) throw new Error("pin-pytools needs Podman or Docker");
  const work = mkdtempSync(path.join(tmpdir(), "pin-pytools-"));
  writeFileSync(path.join(work, "requirements.in"), readFileSync(path.join(dir, "requirements.in")));
  const r = await run({
    command: rt.name,
    args: ["run", "--rm", "-v", `${work}:/w`, imageRef("python"), "sh", "-c",
      "pip install --quiet --disable-pip-version-check --dry-run --ignore-installed --report /w/report.json -r /w/requirements.in"],
    cwd: "/", inheritEnv: ["PATH", "HOME", "XDG_RUNTIME_DIR", "CONTAINER_HOST", "DOCKER_HOST"], timeoutMs: 15 * 60 * 1000,
  });
  if (r.outcome !== "ok") throw new Error(`pip resolve failed: ${r.stderr.toString()}`);
  const report = JSON.parse(readFileSync(path.join(work, "report.json"), "utf8")) as Report;
  rmSync(work, { recursive: true, force: true });

  const lines: string[] = [];
  const pkgs = report.install.map((p) => ({ name: norm(p.metadata.name), version: p.metadata.version }))
    .sort((a, b) => compareCodePoints(a.name, b.name));
  for (const p of pkgs) {
    const res = await fetch(`https://pypi.org/pypi/${p.name}/${p.version}/json`);
    if (!res.ok) throw new Error(`PyPI ${p.name}==${p.version}: ${res.status}`);
    const rel = (await res.json()) as PypiRelease;
    const hashes = [...new Set(rel.urls.map((u) => u.digests.sha256))].sort(compareCodePoints);
    if (hashes.length === 0) throw new Error(`${p.name}==${p.version}: no files on PyPI`);
    lines.push(`${p.name}==${p.version} \\`, ...hashes.map((h, i) => `    --hash=sha256:${h}${i < hashes.length - 1 ? " \\" : ""}`));
  }
  const header = "# toolchain/py-tools/requirements.txt: GENERATED by scripts/pin-pytools.ts. Do not edit by hand.\n" +
    "# Exact tree resolved in the pinned Python image; every PyPI file hash per version (all platforms).\n" +
    "# Installed in the toolchain image with: pip install --require-hashes --no-deps -r requirements.txt\n";
  writeFileSync(path.join(dir, "requirements.txt"), `${header}${lines.join("\n")}\n`);
  process.stdout.write(`pinned ${String(pkgs.length)} python packages\n`);
}

if (process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
