// Readiness for AI-assisted development (2026-10-08): suppressions, TS strictness, CI checks,
// agent instruction files, from a plain file scan.

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { listFiles } from "../../src/lanes/steps.js";
import { readinessMetrics } from "../../src/review/readiness.js";
import { tmpDir } from "../helpers/tmp.js";

function repo(files: Record<string, string>): string {
  const root = tmpDir();
  for (const [f, body] of Object.entries(files)) {
    mkdirSync(path.dirname(path.join(root, f)), { recursive: true });
    writeFileSync(path.join(root, f), body);
  }
  return root;
}

describe("readinessMetrics", () => {
  it("counts production suppressions by kind (as any in TypeScript only), per 1,000 lines, top files first; tests and generated apart", () => {
    const root = repo({
      "src/a.ts": "// eslint-disable-next-line no-eval\nconst x = y as any; // @ts-ignore\n",
      "src/b.js": "const z = w as any; // not TypeScript: not counted\n",
      "app/c.py": "import os  # noqa\nx = f()  # type: ignore\n",
      "src/a.test.ts": "const m = x as any; const n = y as any;\n",
      "src/routeTree.gen.ts": "const r = z as any;\n",
      "src/api.ts": "// @generated by protoc\nconst q = v as any;\n",
    });
    const census = { "src/a.ts": { code: 2, language: "TypeScript" }, "src/b.js": { code: 1, language: "JavaScript" }, "app/c.py": { code: 2, language: "Python" },
      "src/a.test.ts": { code: 1, language: "TypeScript" }, "src/routeTree.gen.ts": { code: 1, language: "TypeScript" }, "src/api.ts": { code: 2, language: "TypeScript" } };
    const r = readinessMetrics(root, listFiles(root), census) as { suppressions: { total: number; tests: number; generated: number; per_kloc_x10: number; by_kind: Record<string, number>; top_files: { file: string; count: number }[] } };
    assert.deepEqual(r.suppressions.by_kind, { "eslint-disable": 1, "as any": 1, "@ts-ignore": 1, noqa: 1, "type: ignore": 1 });
    assert.equal(r.suppressions.total, 5, "production code only");
    assert.deepEqual([r.suppressions.tests, r.suppressions.generated], [2, 2], "tests and generated (by name, by header) counted apart");
    assert.equal(r.suppressions.per_kloc_x10, 10000);
    assert.deepEqual(r.suppressions.top_files, [{ file: "src/a.ts", count: 3 }, { file: "app/c.py", count: 2 }]);
  });

  it("reads tsconfig as JSONC; strict on/off/inherited; CI checks; agent files", () => {
    const root = repo({
      "tsconfig.json": `{\n  // shared settings\n  "compilerOptions": { "strict": true, "noUncheckedIndexedAccess": true, },\n}\n`,
      "apps/web/tsconfig.json": `{ "extends": "../../tsconfig.json", "compilerOptions": {} }`,
      "apps/api/tsconfig.json": `{ "compilerOptions": { "strict": false /* legacy */ } }`,
      ".github/workflows/ci.yml": "jobs:\n  check:\n    steps:\n      - run: pnpm lint\n      - run: pnpm vitest run\n",
      "AGENTS.md": "# rules\n", ".cursor/rules/style.mdc": "x\n",
    });
    const r = readinessMetrics(root, listFiles(root), {}) as {
      typescript: { configs: { file: string; strict: string; no_unchecked_indexed_access: boolean }[] }; ci: { files: string[]; lint: boolean; types: boolean; tests: boolean }; agent_files: string[];
    };
    assert.deepEqual(r.typescript.configs.map((c) => [c.file, c.strict, c.no_unchecked_indexed_access]),
      [["apps/api/tsconfig.json", "off", false], ["apps/web/tsconfig.json", "inherited", false], ["tsconfig.json", "on", true]]);
    assert.deepEqual([r.ci.files, r.ci.lint, r.ci.types, r.ci.tests], [[".github/workflows/ci.yml"], true, false, true]);
    assert.deepEqual(r.agent_files, [".cursor/rules/style.mdc", "AGENTS.md"]);
  });
});
